### PR TITLE
WIP: Support M1 / arm64

### PR DESCRIPTION
**Pull request by larsoner**
I want to have native support for the `napari/label/bundle_tools` forked `constructor` on ARM64 / M1, because I want to be able to debug natively some constructor commands that make use of keys like `reverse_domain_identifier` that don't exist yet in the official installer. (Currently on M1 I'm stuck with the un-forked/original constructor, and it complains about these keys being present, so to test I need to comment them out.)

I wasn't sure how to get the tickbot to do the migration, so I:

1. looked in https://napari.org/developers/packaging.html#details-of-our-constructor-stack-fork and saw this is probably where the constructor is made
2. read https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/ about some commands to use
3. tried to implement them

Let me know if this isn't a good idea / the right idea. But I'm hoping a rerender command will automagically make things work here...

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
... and of course that command probably does not work unless it's a PR on conda-forge :(

Any ideas how to get native M1 builds going for this fork?

**Comment by larsoner** [comment]
Okay, following https://conda-forge.org/docs/maintainer/updating_pkgs.html#dev-rerender-local I ran `conda smithy rerender -c auto` and it at least changed some stuff, but also errored. I'll continue looking

cc @jakirkham in case you have ideas

**Comment by hoechenberger** [comment]
@jaimergp FYI @larsoner has been working with me on MNE-Python installers based on your `constructor` fork

**Comment by larsoner** [comment]
Okay I got `conda smithy rerender -c auto` to work locally on my M1 machine (was getting weird errors on Linux for some unknown reason). If someone can approve the CI run here, we could see if things go green!

**Comment by larsoner** [comment]
Locally on M1 I was able to do on this PR:
```console
$ export OSX_SDK_DIR=SDKs
$ python build-locally.py
...
8. osx_arm64_python3.9.____cpython
...
> 8
selected osx_arm64_python3.9.____cpython
...
```
But eventually it fails in testing:
```
pkgbuild: Wrote package to /Users/larsoner/.conda/constructor/osx-arm64/built_pkgs/cacheclean.pkg
productbuild: Wrote synthesized distribution to /Users/larsoner/.conda/constructor/osx-arm64/built_pkgs/distribution.xml
productbuild: Wrote product to /var/folders/q3/m4sdprkd5658j79sssw9byp00000gn/T/tmpagg6e7ld/osxpkgtest-1.2.3-MacOSX-arm64.pkg
done
Successfully created '/var/folders/q3/m4sdprkd5658j79sssw9byp00000gn/T/tmpagg6e7ld/osxpkgtest-1.2.3-MacOSX-arm64.pkg'.
--- STDERR ---
Warning: key 'attempt_hardlinks' is obsolete.
  Its value 'True' is being ignored.
---- testing osxpkgtest-1.2.3-MacOSX-arm64.pkg
pkgutil --expand /var/folders/q3/m4sdprkd5658j79sssw9byp00000gn/T/tmpagg6e7ld/osxpkgtest-1.2.3-MacOSX-arm64.pkg /var/folders/q3/m4sdprkd5658j79sssw9byp00000gn/T/tmpagg6e7ld/tmpks374s5o
--- STDOUT ---

Some examples failed!
Assets saved in: /var/folders/q3/m4sdprkd5658j79sssw9byp00000gn/T/tmpagg6e7ld
Tests failed for constructor-4.0b1-py39h4ad7db3_0.tar.bz2 - moving package to /Users/larsoner/python/constructor-feedstock/miniforge3/conda-bld/broken
WARNING:conda_build.build:Tests failed for constructor-4.0b1-py39h4ad7db3_0.tar.bz2 - moving package to /Users/larsoner/python/constructor-feedstock/miniforge3/conda-bld/broken
TESTS FAILED: constructor-4.0b1-py39h4ad7db3_0.tar.bz2
```
So who knows if it will pass here... in any case, it would be nice to have 3.10 builds, too, but when I add `python:` with `- 3.10` to `recipe/conda_build_config.yaml` and rerender, it complains about 3.10 not being available, presumably for conda-standalone (?).

**Comment by jaimergp** [comment]
Hi @larsoner, this feedstock is outside conda-forge so it doesn't have any of the machinery we are used to there (bots, rerenders, etc). This is just our "temporary" poorman's attempt at adding this. If you need M1 native tools, I need to build them locally and upload them to that label manually. What I do for napari is to cross-build with `constructor --platform`.

The errors in your CI are probably a bit above; there must be an example which is failing.

**Comment by jaimergp** [comment]
Yep, I reproduced it locally, the problem is the `multienvs` example:

```
--- STDERR ---
Traceback (most recent call last):
  File "$PREFIX/bin/constructor", line 11, in <module>
    sys.exit(main())
  File "$PREFIX/lib/python3.9/site-packages/constructor/main.py", line 259, in main
    main_build(dir_path, output_dir=out_dir, platform=args.platform,
  File "$PREFIX/lib/python3.9/site-packages/constructor/main.py", line 120, in main_build
    fcp_main(info, verbose=verbose, dry_run=dry_run, conda_exe=conda_exe)
  File "$PREFIX/lib/python3.9/site-packages/constructor/fcp.py", line 458, in main
    has_conda, licenses, extra_envs_info) = _main(
  File "$PREFIX/lib/python3.9/site-packages/constructor/fcp.py", line 372, in _main
    precs = _solve_precs(
  File "$PREFIX/lib/python3.9/site-packages/constructor/fcp.py", line 309, in _solve_precs
    precs = list(solver.solve_final_state())
  File "$PREFIX/lib/python3.9/site-packages/conda/core/solve.py", line 313, in solve_final_state
    ssc = self._add_specs(ssc)
  File "$PREFIX/lib/python3.9/site-packages/conda/core/solve.py", line 603, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "$PREFIX/lib/python3.9/site-packages/conda/resolve.py", line 555, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "$PREFIX/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
    return f(*args, **kwds)
  File "$PREFIX/lib/python3.9/site-packages/conda/resolve.py", line 576, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "$PREFIX/lib/python3.9/site-packages/conda/resolve.py", line 288, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - python=3.7
```

On arm64, [python 3.7 does not exist](https://github.com/jaimergp/constructor/blob/939b89ca6bbdaebd2d59679b048d041d596db97c/examples/multienvs/construct.yaml#L7), so it fails to solve that one. I'll update that example so it doesn't use it.

**Comment by larsoner** [comment]
Hmm, okay... maybe our effort would be better spent migrating this stuff to the upstream `constructor` package, then!

**Comment by hoechenberger** [comment]
> Hmm, okay... maybe our effort would be better spent migrating this stuff to the upstream `constructor` package, then!

... or create a community-maintained fork. Willingness to merge even simple PRs upstream seems to be very limited. ☹️

**Comment by jaimergp** [comment]
I raised the situation on the conda community call yesterday and I think we might unblock this soon. The creation of a `constructor` team will be called for a vote, and from there on we can start maintaining/reviewing `constructor`!

If you want to be part of the discussion and/or team, let me know!

**Comment by hoechenberger** [comment]
This is amazing news, @jaimergp!!! Thanks for investing so much time in this!

**Comment by hoechenberger** [comment]
> If you want to be part of the discussion and/or team, let me know!

+1 from my side!

**Comment by hmaarrfk** [comment]
@jaimergp please keep me up to date on the constructor team front.

**Comment by hoechenberger** [comment]
Same from my end. And I suppose @larsoner would also be highly interested!!

**Comment by hoechenberger** [comment]
Same from my end. And I suppose @larsoner would also be highly interested!!

**Comment by hmaarrfk** [comment]
i often dreamed of forking it as [`constrictor`](https://en.wikipedia.org/wiki/Boa_constrictor) ^_^

**Comment by hoechenberger** [comment]
> i often dreamed of forking it as [`constrictor`](https://en.wikipedia.org/wiki/Boa_constrictor) ^_^

And if that one fails too and needs a reboot ... `restrictor` 🐍

**Comment by larsoner** [comment]
Sure I'm happy to be on the team! I'll close this for now and hopefully we can start merging upstream soon

**Comment by hmaarrfk** [comment]
where is the repo for this team again? sorry, i often lose repos.

**Comment by larsoner** [comment]
@hmaarrfk you are probably looking for one of these:

https://github.com/conda/constructor
https://github.com/orgs/conda/teams/constructor/members

**Comment by hmaarrfk** [comment]
i feel like i don't have access to this conda team.

I also feel like there was an other thread somewhere.

**Comment by jaimergp** [comment]
@hmaarrfk check here! https://github.com/conda-incubator/governance/issues/53

**Comment by hmaarrfk** [comment]
thank you!

**Pull request closed without merging**
